#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

apt-get -y update
apt-get -y install haproxy=1.6.\*
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 100.26.136.33:80
        server 64820-web-02 54.90.34.106:80
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
